spring:
  application:
    name: user-service

  config:
    import: configserver:http://localhost:8085
    fail-fast: true  # Fail if the Config Server is not available   # Fail immediately if config server is unreachable