server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_service
    username: rahul
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update